create table ACT_RE_DEPLOYMENT
(
    ID_                varchar(64)             not null
        primary key,
    NAME_              varchar(255)            null,
    CATEGORY_          varchar(255)            null,
    KEY_               varchar(255)            null,
    TENANT_ID_         varchar(255) default '' null,
    DEPLOY_TIME_       timestamp(3)            null,
    DERIVED_FROM_      varchar(64)             null,
    DERIVED_FROM_ROOT_ varchar(64)             null,
    ENGINE_VERSION_    varchar(255)            null
)
    collate = utf8mb3_bin;

INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('102501', null, null, null, '', '2023-02-22 05:12:46.983', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105006', null, null, null, '', '2023-02-22 10:25:56.686', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105027', null, null, null, '', '2023-02-22 10:27:34.892', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105031', null, null, null, '', '2023-02-22 10:29:41.589', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105057', null, null, null, '', '2023-02-22 10:34:41.164', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105073', null, null, null, '', '2023-02-22 10:38:48.886', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105082', null, null, null, '', '2023-02-22 10:41:25.405', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105091', null, null, null, '', '2023-02-22 10:45:24.238', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('105095', null, null, null, '', '2023-02-22 10:45:34.451', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('107501', null, null, null, '', '2023-02-22 10:46:43.809', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('115001', null, null, null, '', '2023-02-22 11:51:06.296', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('12501', null, null, null, '', '2022-11-07 05:20:01.233', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('32501', null, null, null, '', '2022-11-09 11:27:18.324', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('35001', null, null, null, '', '2022-11-09 11:39:32.994', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('37501', null, null, null, '', '2022-11-09 11:49:26.399', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('5001', null, null, null, '', '2022-11-06 13:09:25.241', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('85003', null, null, null, '', '2022-12-29 02:42:20.019', null, null, null);
INSERT INTO workflow.ACT_RE_DEPLOYMENT (ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, DERIVED_FROM_, DERIVED_FROM_ROOT_, ENGINE_VERSION_) VALUES ('90004', null, null, null, '', '2022-12-29 03:30:03.984', null, null, null);
