create table ACT_RE_PROCDEF
(
    ID_                     varchar(64)             not null
        primary key,
    REV_                    int                     null,
    CATEGORY_               varchar(255)            null,
    NAME_                   varchar(255)            null,
    KEY_                    varchar(255)            not null,
    VERSION_                int                     not null,
    DEPLOYMENT_ID_          varchar(64)             null,
    RESOURCE_NAME_          varchar(4000)           null,
    DGRM_RESOURCE_NAME_     varchar(4000)           null,
    DESCRIPTION_            varchar(4000)           null,
    HAS_START_FORM_KEY_     tinyint                 null,
    HAS_GRAPHICAL_NOTATION_ tinyint                 null,
    SUSPENSION_STATE_       int                     null,
    TENANT_ID_              varchar(255) default '' null,
    ENGINE_VERSION_         varchar(255)            null,
    DERIVED_FROM_           varchar(64)             null,
    DERIVED_FROM_ROOT_      varchar(64)             null,
    DERIVED_VERSION_        int          default 0  not null,
    constraint ACT_UNIQ_PROCDEF
        unique (KEY_, VERSION_, DERIVED_VERSION_, TENANT_ID_)
)
    collate = utf8mb3_bin;

INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:10:107504', 1, 'http://activiti.org/bpmn', '创建投标保证金', 'createBidSecurity', 10, '107501', 'bid.bpmn20.xml', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:11:115004', 1, 'http://activiti.org/bpmn', '创建投标保证金', 'createBidSecurity', 11, '115001', 'bid.bpmn20.xml', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:1:102504', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 1, '102501', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:2:105009', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 2, '105006', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:3:105030', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 3, '105027', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:4:105034', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 4, '105031', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:5:105060', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 5, '105057', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:6:105076', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 6, '105073', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:7:105085', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 7, '105082', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:8:105094', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 8, '105091', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('createBidSecurity:9:105098', 1, 'http://bpmn.io/schema/bpmn', '创建投标保证金', 'createBidSecurity', 9, '105095', 'bid.bpmn', 'bid.createBidSecurity.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:1:5004', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 1, '5001', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:2:12504', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 2, '12501', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:3:32504', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 3, '32501', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:4:35004', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 4, '35001', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:5:37504', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 5, '37501', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:6:85006', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 6, '85003', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
INSERT INTO workflow.ACT_RE_PROCDEF (ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, TENANT_ID_, ENGINE_VERSION_, DERIVED_FROM_, DERIVED_FROM_ROOT_, DERIVED_VERSION_) VALUES ('process_1667737476222:7:90007', 1, 'http://activiti.org/bpmn', '流程kkkkk', 'process_1667737476222', 7, '90004', 'Invoice.bpmn20.xml', 'Invoice.process_1667737476222.png', null, 0, 1, 1, '', null, null, null, 0);
